version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - alxnet
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - alxnet
  web:
    build: ./
    command: gunicorn alx_listing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    networks:
      - alxnet
  worker:
    build: ./
    command: celery -A alx_listing worker -l info
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
    networks:
      - alxnet
volumes:
  db_data:
networks:
  alxnet:
